language: java

jdk:
  - openjdk14

sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ivanmaleev@inbox.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
  - postgresql

# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:

  global:

      - CODECOV_TOKEN="292500cc-a8b4-4077-a643-1a3d4fbaeec3"