insert into role (name) values ('Admin');
insert into role (name) values ('Director');
insert into users (name, role_id) values ('Ivan', 1);
insert into users (name, role_id) values ('Anton', 2);
insert into rules (name) values ('Sell');
insert into rules (name) values ('Buy');
insert into role_rules (role_id, rules_id) values (1,1);
insert into role_rules (role_id, rules_id) values (1,2);
insert into role_rules (role_id, rules_id) values (2,1);
insert into role_rules (role_id, rules_id) values (2,2);
insert into category (name) values ('Important');
insert into category (name) values ('Not important');
insert into state (name) values ('Start');
insert into state (name) values ('Finish');
insert into item (name, users_id, category_id, state_id) values ('Letter', 1, 2, 1);
insert into item (name, users_id, category_id, state_id) values ('Letter 2', 2, 1, 2);
insert into item (name, users_id, category_id, state_id) values ('Letter 3', 2, 2, 2);
insert into comments (text, item_id) values ('All good', 3);
insert into comments (text, item_id) values ('Reply', 2);
insert into attachs (file_name, item_id) values ('file.txt', 1);